## Configuracao o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
## Configuracao JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect