CREATE TABLE tb_usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    username varchar(100) not null unique,
    email_corporativo varchar(100) unique,
    password varchar(250) not null,
    situacao char(1) not null default 'I',
    role varchar(5) not null
);