
CREATE TABLE tb_funcionario (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    nome varchar(250) not null,
    rg varchar(15),
    cpf varchar(11) not null,
    genero varchar(1),
    data_nascimento date,
    email varchar(100),
    email_corporativo varchar(100) not null,
    celular varchar(11) not null,
    telefone varchar(11),
    pais_origem varchar(3),
    cep varchar(10),
    logradouro varchar(100),
    numero varchar(10),
    bairro varchar(100),
    cidade varchar(100),
    estado varchar(2),
    funcao varchar(3),
    departamento varchar(100),
    matricula varchar(20),
    usuario_id bigint,
 	medico_id bigint unique,
    data_admissao date,

    constraint fk_medico_funcionario FOREIGN KEY (medico_id) REFERENCES tb_medico(id)
);
