CREATE TABLE tb_paciente (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    nome varchar(250) not null,
    cpf varchar(11) not null,
    email varchar(100),
    celular varchar(11) not null,
    telefone varchar(11),
    rg varchar(15),
    pais_origem varchar(3),
    genero varchar(1),
    data_nascimento date,
    cep varchar(10),
    logradouro varchar(100),
    numero varchar(10),
    bairro varchar(100),
    cidade varchar(100),
    estado varchar(2)
);