CREATE TABLE tb_medico_especialidade (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    id_medico bigint not null,
    id_especialidade bigint not null,
    situacao boolean not null default true,
    principal boolean not null default false,
    data_criacao timestamp not null default now(),
    constraint fk_medico foreign key (id_medico) references tb_medico(id),
    constraint fk_especialidade foreign key (id_especialidade) references tb_especialidade(id)
);

CREATE UNIQUE INDEX idx_medico_especialidade_principal  ON tb_medico_especialidade (id_medico) WHERE (principal = true);
