CREATE TABLE tb_medico (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    crm varchar(10),
    crm_estado varchar(2),
    crm_situacao char(1) default 'A',
    instituicao_graduacao varchar(100),
    situacao_pos char(1) default 'N',
    instituicao_pos varchar(100),
    situacao_mestrado char(1) default 'N',
    instituicao_mestrado varchar(100),
    situacao_doutorado char(1) default 'N',
    instituicao_doutorado varchar(100)
);