CREATE TABLE tb_especialidade (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    descricao varchar(200) not null unique,
    rqe varchar(10),
    cbo varchar(20),
    tiss varchar(20),
    situacao boolean default 'A',
    data_criacao timestamp default now()
);