CREATE TABLE tb_especialidade (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    descricao varchar(200) not null unique,
    cbo varchar(20),
    tuss varchar(20),
    situacao boolean default true,
    data_criacao timestamp default now()
);

comment on column tb_especialidade.descricao is 'Nome clínico da especialidade';
comment on column tb_especialidade.cbo is 'Código da Classificação Brasileira de Ocupações (Ministério do Trabalho)';
comment on column tb_especialidade.tuss is 'Código da Terminologia Unificada da Saúde Suplementar (ANS) para convênios';
comment on column tb_especialidade.situacao is 'Situação da especialidade.';
