CREATE TABLE tb_especialidade (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    descricao varchar(200) not null unique,
    cbo varchar(20),
    tiss varchar(20),
    situacao boolean default true,
    data_criacao timestamp default now()
);
