CREATE TABLE tb_funcionario (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    nome varchar(250) not null,
    rg varchar(15),
    cpf varchar(11) not null,
    genero varchar(1),
    data_nascimento date,
    email varchar(100) not null,
    celular varchar(11) not null,
    telefone varchar(11),
    pais_origem varchar(3),
    cep varchar(10),
    logradouro varchar(100),
    numero varchar(10),
    bairro varchar(100),
    cidade varchar(100),
    estado varchar(2),
    funcao varchar(3),
    departamento varchar(100),
    matricula varchar(20),
    usuario_id bigint,

    constraint fk_funcionario_id foreign key (usuario_id) references tb_usuario(id)
);

--    crm varchar(10),
--    crm_estado varchar(2),
--    instituicao_graduacao varchar(100),
--    status_pos varchar(2),
--    instituicao_pos varchar(100),
--    status_mestrado varchar(2),
--    instituicao_mestrado varchar(100),
--    status_doutorado varchar(2),
--    instituicao_doutorado varchar(100)