CREATE TABLE tb_convenio (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    descricao varchar(100) not null unique,
    situacao varchar(1) default 'A',
    data_criacao timestamp default now()
);