CREATE TABLE tb_convenio (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    razao_social varchar(100) not null,
    nome_fantasia varchar(100) not null,
    cnpj varchar(14) not null unique,
    registro_ans varchar(20) not null,
    telefone varchar(11),
    email varchar(100),
    situacao varchar(1) default 'A',
    data_criacao timestamp default now()
);