CREATE TABLE tb_plano (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    descricao varchar(50) not null,
    codigo_ans varchar(20) not null,
    acomodacao varchar(1) not null default 'A',
    abrangencia varchar(1) not null default 'N',
    situacao varchar(1) not null default 'I',
    data_criacao timestamp default now()
);

ALTER TABLE tb_plano ADD COLUMN id_convenio bigint, ADD FOREIGN KEY (id_convenio) REFERENCES tb_convenio(id);