CREATE TABLE tb_departamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    descricao varchar(50) not null,
    situacao char(1) not null default 'A',
    created_at timestamp default now(),
    updated_at timestamp default now()
);
