apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinic-selector
  template:
    metadata:
      labels:
        app: clinic-selector
    spec:
      containers:
        - name: clinic-api
          image: mauriciocarvalhoac/clinic-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://service-db-clinic:5432/clinic_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"