name: Pipeline CI/CD

on:
  push:
    branches: [ "master", "env/homologacao" , "feature/sprint002/001-configuracao-cloud-native" ]

jobs:
  construir:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:17-alpine
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/clinic
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
          SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION: "true"
          LOGGING_LEVEL_ORG_FLYWAYDB: DEBUG
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Executar build com Maven
        run: mvn clean package

      - name: Rodar um comando
        run: echo "Concluído"